secondproject/urls.py
from django.contrib import admin
from django.urls import path,include
from hr_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hr_app/',include('hr_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/',views.home,name='Home'),
    path('employee/',views.employee,name='Employee'),
    path('contact/',views.contact_form,name='Contact'),
    path('empdata/',views.employee_list,name='Emp'),
    path('logout/',views.logout,name='Logout'),
    path('hr/',views.hr,name='Hr'),
    # path('news/',views.news,name='News'),
    path('calender/',views.submit_holiday, name='Submit_holiday'),
    path('holiday_list/', views.holiday_list, name='List'),
    path('news/',views.submit_news, name='Submit_news'),
    path('news_list/', views.news_list, name='News_list'),
    path('update_employee/<int:pk>/', views.update_employee, name='update_employee'),
    path('delete_employee/<int:pk>/', views.delete_employee, name='delete_employee'),






]

hr_app/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=100)
    empid = models.CharField(max_length=20, unique=True)
    designation = models.CharField(max_length=50)
    date_of_joining = models.DateField()
    department = models.CharField(max_length=50)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    experience = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    
class Holiday(models.Model):
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return f"Holiday on {self.date}"
    
class NewsArticle(models.Model):
    heading = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return(self.heading)

hr_app/forms.py
from django import forms
from hr_app.models import *

class Employeeform(forms.ModelForm):
    class Meta:
        model= Employee
        fields=('__all__')  

class HolidayForm(forms.ModelForm):
    class Meta:
        model = Holiday
        fields = ['date', 'description']
    # Customize the date field widget
    date = forms.DateField(widget= forms.DateInput(attrs={'type': 'date'}))



class NewsForm(forms.ModelForm):
    class Meta:
        model = NewsArticle
        fields = ['heading', 'content']


    

hr_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . import forms 
from . import models
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    return render(request,'hr_app/home.html')

def employee(request):
    return render(request,'hr_app/employee.html')

def employee_list(request):
    employee=models.Employee.objects.all()
    return render(request,'hr_app/users.html',{'employee': employee})


def contact_form(request):
    print("$$$$$$")
    form = forms.Employeeform() 
    if request.method=="POST":
        form = forms.Employeeform(request.POST)
        if form.is_valid():
            print('Form is valid')
            form.save()
            return redirect('/empdata')
        else:
             form = forms.Employeeform()
          
    return render(request,'hr_app/contact.html',{'form': form})


def logout(request):
    return render(request,'hr_app/logout.html')

@login_required
def hr(request):
    return render(request,'hr_app/hr_main.html')


def submit_holiday(request):
    if request.method == 'POST':
        form = forms.HolidayForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/list')  
    else:
        form = forms.HolidayForm()
    return render(request, 'hr_app/calender.html', {'form': form})


def holiday_list(request):
    holidays = models.Holiday.objects.all().order_by('date')
    return render(request, 'hr_app/holiday_list.html', {'holidays': holidays})



def submit_news(request):
    if request.method == 'POST':
        form = forms.NewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/news_list')  
    else:
        form = forms.NewsForm()
    return render(request, 'hr_app/news.html', {'form': form})

def news_list(request):
    news = models.NewsArticle.objects.all()
    return render(request, 'hr_app/news_list.html', {'news': news})

def update_employee(request, pk):
    employee = models.Employee.objects.get(pk=pk)
    if request.method == 'POST':
        form = forms.Employeeform(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('/empdata')
    else:
        form = forms.Employeeform(instance=employee)
    return render(request,'hr_app/contact.html', {'form': form})

def delete_employee(request, pk):
    employee = models.Employee.objects.get(pk=pk)
    employee.delete()
    return redirect('/empdata')

templates/hr_app/calender.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>Holiday Form</title>
    <style>
        .div{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 30vh;
            margin: 0;
        }
        #id_date{
            input-security: date;
        }
        .your-form-class {
            max-width: 35%;
            background-color: #eebfd9; 
            padding: 20px;
            border: 1px solid #737171;
            margin-left: 30%;
            padding-left: 4%; 
            /* display: flexbox;
            flex-direction: column;
            align-items: center; 
            justify-content:center; */
            color: solid rgb(0, 0, 0);
            font-size: 20px;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);


        }
        button[type="submit"] {
            background-color: #000000;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
            margin-right: 8%;
      
        }
        


    </style>
</head>
<body>
    <center><h2 class="h3" style="font-size: 35px">Enter Holiday Information</h2></center>
    
    <div>
        <form method="post" class="your-form-class">
            {% csrf_token %}
            {{ form.as_p }}
            <center><button type="submit">Submit</button></center>
        </form>
    
</div>

</body>
</html>

templates/hr_app/contact.html
{% include 'hr_app/nav.html' %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>Employee_form</title>
    <style>
        /* Apply styles to the entire form */
        .your-form-class {
            max-width: 35%;
            background-color: #eebfd9; 
            padding: 20px;
            border: 1px solid #737171;
            margin-left: 30%;
            padding-left: 9%; 
            /* display: flexbox;
            flex-direction: column;
            align-items: center; 
            justify-content:center; */
            color: solid rgb(0, 0, 0);
            font-size: 20px;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);


        }
    
        /* Apply styles to specific form fields by targeting their IDs or names */
        #id_name {
            width: 50%;
            padding: 10px;
            padding-right: 39px;
            margin-bottom: 10px;
            border: 1px solid #000000;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);

        }
        #id_empid {
            width: 50%;
            padding: 10px;
            padding-right: 45px;
            margin-bottom: 10px;
            border: 1px solid #060000;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);

        }
        input#id_subject {
        padding-right: 28px;
        }
    

        #id_date_of_joining {
            width: 50%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #0d0101;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);

        }
        #id_department {
            width: 50%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #0d0101;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);

        }
        #id_salary {
        width: 50%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #050000;
        box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
        padding-right: 36px;
}
        #id_experience {
            width: 50%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #000000;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
            padding-right: 14px;

        }
        #id_designation {
            width: 50%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #000000;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
            padding-right: 14px;

        }
        
    
        /* Apply styles to the submit button */
        button[type="submit"] {
            background-color: #000000;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
            margin-right: 17%;

            
        }
    </style>
    
</head>
<body>
    <!-- <center><h1 class="h3" style="font-size: 40px" >Contact Us</h1></center> -->
   <center> <h1 class="h3" style="font-size: 40px" >Employee Form</h1></center>
    <br>
    <div>
        <form method="post" class="your-form-class">
            {% csrf_token %}
            {{ form.as_p}}
           
            <a href="{% url 'Home'%}"><center> <button type="submit">Submit</button></center></a>
        </form>
    </div>
&nbsp;&nbsp;&nbsp;&nbsp;


</body>
&nbsp;&nbsp;&nbsp;&nbsp;

<footer>
    <p>&copy; 2023 MSRCOSMOS GROUP</p>
</footer>

</html>

templates/hr_app/employee.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}"> 
<style>
    body {
        /* display: flex;
        justify-content: center;
        align-items: center; */
        height: 100vh;
        margin: 0;
    }
    .div{
        display: flex;
        justify-content: center;
        align-items: center;
        height: 50vh;
        margin: 0;
    }

    .button-container {
        text-align: center;
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #d1b122;
        color: #080106;
        border: none;
        border-radius: 5px;
        margin: 10px;
        cursor: pointer;
        text-decoration: none;
        font-size: 25px;
    }

    .button:hover {
        background-color: #0056b3;
    }
</style>
</head>
<body>
    <br>
    <br>
    <center><h1 class="h3" style="font-size: 35px"> EMPLOYEE MANAGEMENT PORTAL</h1></center>
<div class=" div">
<div class="button-container">
    <a href="/holiday_list"><button class="button">CALENDER HOLIDAYS </button></a>
    &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
    <a href="/news_list"><button class="button">LATEST NEWS</button></a>

</div>
</div>
</body>
   
    <!-- <footer>
         <p>&copy; 2023 MSRCOSMOS GROUP</p>
    </footer> -->
</body>
</html>

templates/hr_app/holiday_list.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>Holiday List</title>
    <style>
        /* Style the table */
        table {
            border-collapse: collapse;
            width: 60%;
            margin: 20px auto;
        }
        table, th, td {
            border: 1px solid #0a0a0a;
        }

        /* Style table headers */
        th {
            background-color: #007bff;
            color: #fff;
            text-align: left;
            padding: 10px;
        }

        /* Style table rows */
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Style table cells */
        td {
            padding: 10px;
        }

        
        .div{
        /* display: flex;
        justify-content:  right; */
        
        height: 20vh;
        margin: 0;
    }

    .button-container {
        text-align: center;padding-left: 23%;
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #d1b122;
        color: #080106;
        border: none;
        border-radius: 5px;
        margin: 10px;
        cursor: pointer;
        text-decoration: none;
        font-size: 25px;
    }

    .button:hover {
        background-color: #0056b3;
    }

    </style>
</head>
<body>
    <center><h2 class="h3" style="font-size: 35px">Holiday List</h2></center>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for holiday in holidays %}
                <tr>
                    <td>{{ holiday.date }}</td>
                    <td>{{ holiday.description }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">No holidays found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
    <div class=" div">
        <div class="button-container">
        
            &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
            <a href="/news_list"><button class="button">LATEST NEWS</button></a>
        
        </div>
        </div>
    

</body>
</html>

templates/hr_app/home.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}"> <!-- Link to your CSS file -->
    
</head>
<body>
    &nbsp;

<!-- <h1>THIS IS HOME PAGE</h1> -->

<!-- <img class="ven" src="{% static 'images/_DSC7431.jpg' %}" alt=""> -->
<!-- <div class="banner">
<img class="banner-image" src="{% static 'images/msr.jpg' %}" alt="Banner Image" > 
</div>
<div class="banner">
    <img class="banner-image" src="{% static 'images/msr1.jpg' %}" alt="Banner Image" > 
    </div> -->
<div class="banner">
    <img class="banner-image" src="{% static 'images/M.jpg' %}" alt="Banner Image" > 
    <!-- <video autoplay loop muted playsinline class="banner-video">
        <source src="{% static 'videos/Venkatesh Maragani.mp4' %}" type="video/mp4">
        Add additional source elements for other formats if needed
        Your browser does not support the video tag.
    </video> -->
</div>
&nbsp;
&nbsp;
&nbsp;

<div >
<h2 class="h2">WELCOME TO MSRCOSMOS GROUP</h2>
<div >
    <p class="p3" >MSRcosmos is a fast-growing global IT services company with unmatched capabilities across the service value chain of cloud,
        data analytics & ai, intelligent automation including enterprise applications. “Promise delivered” is our brand proposition, 
        orchestrated via staunch delivery commitments, pathbreaking solutions, highly differentiated talent, and a methodical approach.
         This belief has enabled MSRcosmos to be a preferred partner of choice for many customers across diverse industries
          in USA, Europe, India, and Australia.</p>
</div>
<!-- <h2 class="h2">WHY TO CHOOSE US?</h2>
<div class="banner1">
<img class="image" src="{% static 'images/1.webp' %}" alt="1">
<img class="image" src="{% static 'images/2.webp' %}" alt="2">
<img class="image" src="{% static 'images/3.webp' %}" alt="3">
<img class="image" src="{% static 'images/4.webp' %}" alt="4">
</div>
</div> -->

<!-- <div class="banner2">
   <div><p class="banner3">venkatesh maragani </p></div>
   <div><p class="banner3">venkatesh maragani</p></div>
   <div><p class="banner3">venkatesh maragani</p></div>
    <div><p class="banner3">venkatesh maragani</p></div> -->

<!-- </div> -->
</body>
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;

<footer>
    <p>&copy; 2023 MSRCOSMOS GROUP</p>
</footer>
</html>

templates/hr_app/hr_main.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>HR_Section</title>
    <style>
        body {
            /* display: flex;
            justify-content: center;
            align-items: center; */
            height: 100vh;
            margin: 0;
        }
        .div{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 50vh;
            margin: 0;
        }

        .button-container {
            text-align: center;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #d1b122;
            color: #080106;
            border: none;
            border-radius: 5px;
            margin: 10px;
            cursor: pointer;
            text-decoration: none;
            font-size: 25px;
        }

        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <br>
    <br>
    <center><h1 class="h3" style="font-size: 35px">HR MANAGEMENT PORTAL</h1></center>
    <div class=" div">
    <div class="button-container">
        <a href="{% url 'Contact'%}"><button class="button">ADD EMPLOYEE</button></a>
        &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
        <a href="{% url 'Emp'%}"><button class="button">VIEW EMP DATA</button></a>
        <br>
        <br>
        <br>
        <br>
        <a href="/news"><button class="button">ADD LATEST NEWS</button></a>
        &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp
        <a href="/calender"><button class="button">ADD CALENDER</button></a>
        
    </div>
</div>
</body>
</html> 

templates/hr_app/logout.html
<!DOCTYPE html>
<html>
<head>
    <title>Logout</title>
</head>
<body>
    <h1>Logout</h1>
    <h2>You have been successfully logged out.</h2>
    <h4>Thank you for using our services. You can <a href="/accounts/login/"> &nbsp;Login</a> &nbsp; again if needed.</h4>
</body>
</html>

templates/hr_app/nav.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* Reset some default styles for better consistency */
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        /* Style the navigation bar */
        .navbar {
            background-color: rgba(1, 1, 29, 0.826);
            overflow: hidden;
            position: sticky;
        }
        .navbar .sticky{
            position: fixed;
            top: 0;
            width: 100%;

        }

        /* Navbar links */
        .navbar a {
            float:left;
            display: block;
            color: rgb(255, 255, 255);
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            text-shadow: 2px 2px 4px rgb(0, 0, 0)
        }
        

        /* On hover, the links will change color */
        .navbar a:hover {
            background-color: #cf6d0b;
        }

        .navbar a img {
            
            width: 30px; /* Adjust the width as needed */
            height: 30; /* Automatically adjust the height to maintain aspect ratio */
            background-color: transparent !important;
            margin-right: 10px; /* Add some spacing between the logo and navigation links */
        }
       
    </style>
</head>
<body>
    <script>
        window.addEventListener("scroll", function() {
    const navbar = document.querySelector(".navbar");
    if (window.scrollY > 100) {
        navbar.classList.add("sticky");
    } else {
        navbar.classList.remove("sticky");
    }
});

    </script>
    <div class="navbar">
        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-heart-eyes-fill" viewBox="0 0 16 16">
            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zM4.756 4.566c.763-1.424 4.02-.12.952 3.434-4.496-1.596-2.35-4.298-.952-3.434zm6.559 5.448a.5.5 0 0 1 .548.736A4.498 4.498 0 0 1 7.965 13a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .548-.736h.005l.017.005.067.015.252.055c.215.046.515.108.857.169.693.124 1.522.242 2.152.242.63 0 1.46-.118 2.152-.242a26.58 26.58 0 0 0 1.109-.224l.067-.015.017-.004.005-.002zm-.07-5.448c1.397-.864 3.543 1.838-.953 3.434-3.067-3.554.19-4.858.952-3.434z"/>
          </svg> -->
        <!-- <a href="/FP_App/home"><img  src="{% static 'images/_DSC7431.jpg' %}" alt="Logo"></a> --> 
        <a href="{% url 'Home'%}"><img src="{% static 'images/MSR Cosmos Group.jpg' %}" class="logo-dark" alt="MSRcosmos" width="800" height="10" loading="eager">
        </a>
        <!-- <a href="/FP_App/home"><img  src="" alt="Logo"></a> -->
        <a href="{% url 'Home'%}">Home</a>
        <a href="{% url 'Hr'%}">HR Manager</a>
        <a href="{% url 'Employee'%}">Employee</a>
        {% if user.is_authenticated %}
            <!-- User is logged in -->
            <!-- <a href="{% url 'logout' %}">Logout</a> -->
        <a href="/logout" style="float: right; " style="padding-right: 10%;">Logout</a> &nbsp; &nbsp;

        {% else %}
            <!-- User is not logged in -->
            <!-- <a href="{% url 'login' %}">Login</a> -->
            <a href="/accounts/login" style="float: right; " >Login</a> &nbsp; &nbsp;

        {% endif %}



    
    </div>
    
</body>
</html>

templates/hr_app/news.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>Latest News</title>
    <style>
        .div{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 30vh;
            margin: 0;
        }
        #id_date{
            input-security: date;
        }
        .your-form-class {
            max-width: 35%;
            background-color: #eebfd9; 
            padding: 17px;
            border: 1px solid #737171;
            margin-left: 31%;
            padding-left: 4%; 
            /* display: flexbox;
            flex-direction: column;
            align-items: center; 
            justify-content:center; */
            color: solid rgb(0, 0, 0);
            font-size: 20px;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);


        }
        button[type="submit"] {
            background-color: #000000;
            color: white;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            box-shadow: 0px 0px 10px rgba(5, 5, 5, 0.5);
            margin-right: 8%;
      
        }
    </style>

</head>
<body>
    
    <center><h2 class="h3" style="font-size: 35px">Latest News</h2></center>
    <div>
    <form method="post" class="your-form-class">
        {% csrf_token %}
        {{ form.as_p }}
        <center><button type="submit">Submit</button></center>
    </form>
</div>
</body>
</html>

templates/hr_app/news_list.html
<!DOCTYPE html>
{% include 'hr_app/nav.html' %}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title> News List</title>
    <style>
        /* Style the table */
        table {
            border-collapse: collapse;
            width: 60%;
            margin: 20px auto;
        }
        table, th, td {
            border: 1px solid #0a0a0a;
        }

        /* Style table headers */
        th {
            background-color: #007bff;
            color: #fff;
            text-align: left;
            padding: 10px;
        }

        /* Style table rows */
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        /* Style table cells */
        td {
            padding: 10px;
        }
        .div{
        /* display: flex;
        justify-content:  right; */
        
        height: 20vh;
        margin: 0;
    }

    .button-container {
        text-align: center;padding-left: 23%;
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #d1b122;
        color: #080106;
        border: none;
        border-radius: 5px;
        margin: 10px;
        cursor: pointer;
        text-decoration: none;
        font-size: 25px;
    }

    .button:hover {
        background-color: #0056b3;
    }


</style>
</head>
<body>
    <center><h2 class="h3" style="font-size: 35px">News List</h2></center>
    <table>
        <thead>
            <tr>
                <th>heading</th>
                <th>content</th>
            </tr>
        </thead>
        <tbody>
            {% for new in news %}
                <tr>
                    <td>{{ new.heading }}</td>
                    <td>{{ new.content  }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">No news found.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class=" div">
        <div class="button-container">
            <a href="/holiday_list"><button class="button">CALENDER HOLIDAYS </button></a>
            <!-- &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
            <a href="/news_list"><button class="button">LATEST NEWS</button></a>
         -->
        </div>
        </div>
    
</body>
</html>

templates/hr_app/users.html
{% include 'hr_app/nav.html' %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <title>Employeee Data</title>
    <style>
        /* Add your CSS styles here */
        table {
            width: 80%;
            border-collapse: collapse;
            margin: 20px auto;
        }

        table, th, td {
            border: 1px solid #eba9a9;
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #e86d6d;
        }

        .div{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 10vh;
            margin: 0;
        }

        .button-container {
            text-align: center;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #e86d6d;
            color: #080106;
            border: none;
            border-radius: 5px;
            margin: 10px;
            cursor: pointer;
            text-decoration: none;
            font-size: 25px;
        }

        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <center><h1 class="h3" style="font-size: 40px">Employeee Data</h1></center>
    <div>
        {% if employee %}
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Emp ID</th>
                    <th>Designation</th>
                    <th>Date of joining</th>
                    <th>Department</th>
                    <th>Salary</th>
                    <th>Experience</th>
                    <th>HR Section</th>


                </tr>
            </thead>
            <tbody>
                {% for emp in employee %}
                    <tr>
                        <td>{{ emp.name }}</td>
                        <td>{{emp.empid }}</td>
                        <td>{{ emp.designation}}</td>
                        <td>{{ emp.date_of_joining }}</td>
                        <td>{{emp.department }}</td>
                        <td>{{emp.salary }}</td>
                        <td>{{emp.experience }}</td>

                        <td><a href="{% url 'update_employee' emp.id %}"><button>Update</button></a> &nbsp; 
                            <a href="{% url 'delete_employee' emp.id %}"><button>Delete</button></a></td>
                        



                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
            <h2>No Users </h2>
        {% endif%}
    </div>
    <div class=" div">
        <div class="button-container">
            <a href="{% url 'Contact'%}"><button class="button">ADD EMPLOYEE</button></a>
            &nbsp &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp&nbsp&nbsp
            <a href="{% url 'Hr'%}"><button class="button">BACK TO HR MANAGER</button></a>
        </div>
    </div>
</body>

&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;
<!-- 
<footer >
    <p>&copy; 2023 MSRCOSMOS GROUP</p>
</footer> -->
</html>